- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - check-requirements
      - release-notes-jobs
    check:
      jobs:
        - freezer-ubuntu-xenial:
            voting: false
        - freezer-centos-7:
            voting: false
        - openstack-tox-pylint
    gate:
      jobs:
        - openstack-tox-pylint
    experimental:
      jobs:
        - freezer-opensuse-423

- job:
    name: freezer-ubuntu-xenial
    parent: legacy-dsvm-base
    run: playbooks/legacy/freezer-ubuntu-xenial/run.yaml
    post-run: playbooks/legacy/freezer-ubuntu-xenial/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/freezer
      - openstack/freezer-api
      - openstack/freezer-web-ui
      - openstack/python-freezerclient
      - openstack/freezer-tempest-plugin

- job:
    name: freezer-centos-7
    parent: legacy-dsvm-base
    run: playbooks/legacy/freezer-centos-7/run.yaml
    post-run: playbooks/legacy/freezer-centos-7/post.yaml
    timeout: 7800
    nodeset: legacy-centos-7
    required-projects:
      - openstack/devstack-gate
      - openstack/freezer
      - openstack/freezer-api
      - openstack/freezer-web-ui
      - openstack/python-freezerclient
      - openstack/freezer-tempest-plugin

- job:
    name: freezer-opensuse-423
    parent: legacy-dsvm-base
    run: playbooks/legacy/freezer-opensuse-423/run.yaml
    post-run: playbooks/legacy/freezer-opensuse-423/post.yaml
    timeout: 7800
    nodeset: legacy-opensuse-423
    required-projects:
      - openstack/devstack-gate
      - openstack/freezer
      - openstack/freezer-api
      - openstack/freezer-web-ui
      - openstack/python-freezerclient
      - openstack/freezer-tempest-plugin
